unit DefPocb;

interface
{$I Common.inc}

uses
  Winapi.Messages;

const

  //============================================================================
  // General
  //============================================================================

  //------------------------------------ GUI General
  // UI Color Style
  UI_WINDOWS       = 0;
  UI_WIN10_NOR     = 1;
  UI_WIN10_BLACK   = 2;
		
  // UI Language
  LANGUAGE_KOREA   = 0;
  LANGUAGE_VIETNAM = 1;
	
  // Password (암호화 작업을 위한 Default Key)
  PASSWORD_KEY_C1  = 74054;
	PASSWORD_KEY_C2  = 12337;

  HexaChar : array [0..15] of Char =( '0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F' );

  //------------------------------------ Progeam Title
{$IF Defined(POCB_A2CH)}
  PROGRAM_NAME    = 'Auto PUC Inspector (VH Line#1)';
{$ELSEIF Defined(POCB_A2CHv2)}
  PROGRAM_NAME    = 'Auto PUC Inspector (VH Line#1/Type2)';
{$ELSEIF Defined(POCB_A2CHv3)}
  PROGRAM_NAME    = 'Auto PUC Inspector (VH Line#1/CP+ASSY)';
{$ELSEIF Defined(POCB_A2CHv4)}
  PROGRAM_NAME    = 'Auto PUC Inspector (VH Line#2)';
{$ELSEIF Defined(POCB_ATO)}
  PROGRAM_NAME    = 'LENSVN ATO PUC Inspector';
{$ELSEIF Defined(POCB_GAGO)}
  PROGRAM_NAME    = 'LENSVN GAGO PUC Inspector';
{$ELSEIF Defined(POCB_F2CH)}
  PROGRAM_NAME    = 'Foldable PUC Inspector';
{$ENDIF}

  PWD_TYPE_ADMIN = 0;
  PWD_TYPE_PM    = 1;

  //============================================================================
  // System Config
  //    - POCB: 2CH/SYS, JIG:CH:PG:CAM=1:1:1:1
  //    - PG(main) + SPI|QSPI
  //============================================================================

  //------------------------------------ CH/CAM/JIG/PG Count
  CH_CNT   = 2;
  CAM_CNT  = 2;
  JIG_CNT  = 2;
  PG_CNT   = 2;

  //------------------------------------ CH/CAM/JIG/PG Index
  CH_1      = 0;
  CH_2      = 1;
  CH_MAX    = CH_2;
  CH_ALL    = CH_CNT;

  CAM_1     = 0;
  CAM_2     = 1;
  CAM_MAX   = CAM_2;

  JIG_A     = 0;
  JIG_B     = 1;
  JIG_MAX   = JIG_B;
  JIG_ALL   = 2;

  PG_1      = 0;
  PG_2      = 1;
  PG_MAX    = PG_2;

  //------------------------------------ PG/SPI|QSPI Config
  PGSPI_MAIN_PG   = 0;
  PGSPI_MAIN_QSPI = 1;
  {$IF Defined(INSPECTOR_GB) or Defined(INSPECTOR_AC)}  //GB|AC
  PGSPI_MAIN_TYPE = PGSPI_MAIN_QSPI;
  {$ELSE}
  PGSPI_MAIN_TYPE = PGSPI_MAIN_PG;
  {$ENDIF}

  //============================================================================
  //
  //============================================================================

  BCR_LENGTH_DEFAULT  = 13;

  // Zone
  ZONE_NONE     = 0;
  ZONE_LOAD     = 1;
  ZONE_CAMERA   = 2;
  ZONE_UNLOAD   = 3;

  // Config/Model FilePath Type (Common.GetFilePath)
  PATH_TYPE_MODEL       = 0;
  PATH_TYPE_MODEL_PARAM = 1;
  PATH_TYPE_PATTERN     = 2;
	PATH_TYPE_PATGRP      = 3;
	PATH_TYPE_SCRIPT      = 4;

  //
  SEQ_RESULT_CLEAR   = 1;
  SEQ_RESULT_PASS    = 2;
  SEQ_RESULT_FAIL    = 3;
  SEQ_RESULT_WORKING = 4;

  // POCB Flow - PG Download Data Type
  DOWNDATA_BMP          = 0;
  DOWNDATA_POCB_COMPBMP = 1;
  DOWNDATA_POCB_CBDATA  = 2;

  COMPBMP_DOWN_NAME  = 'DOWNBMP';  //'DOWNBMP.raw' -> 'DOWNBMP'

  //
  LOG_TYPE_INFO = 0; //default!!!!
  LOG_TYPE_OK   = 1;
  LOG_TYPE_NG   = 2;
  LOG_TYPE_DIO  = 3;

  SYS_LOG = -1;  // MAX_SYSTEM_LOG

  //
  UNIFORMITY_PATTERN_MAX = 3;  // 0부터 시작이라 Length - 1 //TBD:MERGE?
  UNIFORMITY_POINT_COUNT = 21; //TBD:MERGE?
		
  //============================================================================
  //
  //============================================================================

	//----------------------------------------------------------------------------
  //
	//----------------------------------------------------------------------------

  // Item Type. 구조체가 달라 재일 먼처 체크 할 필요 있음.
  MSG_TYPE_NONE   = 0;
  MSG_TYPE_SCRIPT = 1;
  MSG_TYPE_SWITCH = 2;
  MSG_TYPE_LOGIC  = 3;
  MSG_TYPE_PG     = 4;
  MSG_TYPE_JIG    = 5;
  MSG_TYPE_DIO    = 6;
  MSG_TYPE_ADLINK = 7;
  MSG_TYPE_CA310  = 8;
  MSG_TYPE_HOST   = 9;
  MSG_TYPE_CAMERA = 10;
  MSG_TYPE_MOTION = 11;  //A2CH|F2CH
  MSG_TYPE_DFS    = 12;  //DFS
  MSG_TYPE_EFU    = 13;  //2019-05-02 EFU
  MSG_TYPE_EXLIGHT= 14;
  MSG_TYPE_IONIZER= 15;  //2019-08-23 Ionizer
{$IFDEF HAS_ROBOT_CAM_Z}
  MSG_TYPE_ROBOT  = 16;  //A2CHv3:ROBOT
{$ENDIF}
  MSG_TYPE_DOWNLOAD = 17;  //TBD:MERGE:PG_DOWN? FoldFI(O) POCB(DownloadFwPg)

 	//----------------------------------------------------------------------------
  //
	//----------------------------------------------------------------------------

  MSG_MODE_DISPLAY_CHANNEL        = 0;
  MSG_MODE_DISPLAY_VOLCUR         = 1;
  MSG_MODE_DISPLAY_ALARM          = 2;
  MSG_MODE_DISPLAY_MODELINFO      = 3;
  MSG_MODE_CONTINUETIMER_ENABLE   = 4;
  MSG_MODE_DISPLAY_RCBDATA        = 5;
  MSG_MODE_DISPLAY_STATUS         = 6;  //TBD?

  MSG_MODE_SWITCH_ONOFF           = 7;
  MSG_MODE_TEST_HOST              = 8;
  MSG_MODE_DISPLAY_FLOW           = 9;
  MSG_MODE_DISPLAY_RESULT         = 10;
  MSG_MODE_CH_CLEAR               = 11;
  MSG_MODE_BARCODE_READY          = 12;
  MSG_MODE_TACT_START             = 13;
  MSG_MODE_TACT_END               = 14;
  MSG_MODE_FLOW_START             = 15;
  MSG_MODE_FLOW_STOP              = 16;
  MSG_MODE_POWER_ON               = 17;
  MSG_MODE_POWER_OFF              = 18;
  MSG_MODE_NG_CNT                 = 19;
  MSG_MODE_BTN_ENABLE             = 20;
  MSG_MODE_BTN_DISABLE            = 21;
  MSG_MODE_MODEL_DOWN_START       = 22;
  MSG_MODE_MODEL_DOWN_END         = 23;
  MSG_MODE_MODEL_DOWNLOADING      = 24;
  MSG_MODE_FLOW_STOP_REPORT       = 25;
  MSG_MODE_FLOW_DATA_VIEW         = 26;
  MSG_MODE_MAKE_SUMMARY_CSV       = 27;
  MSG_MODE_SEND_GMES              = 28;
  MSG_MODE_SEND_RSTDONE           = 29;

  MSG_MODE_WORK_DONE              = 30;
  MSG_MODE_WORKING                = 31;
  MSG_MODE_LOG_ON_GUI             = 35;
  MSG_MODE_DISPLAY_CONNECTION     = 36;
  MSG_MODE_TRANS_DOWNLOAD_STATUS  = 37;
  MSG_MODE_UNIT_TT_START          = 38;
  MSG_MODE_UNIT_TT_STOP           = 39;
  MSG_MODE_SHOW_SERIAL_NUMBER     = 40;
  MSG_MODE_DISPLAY_PATTERN        = 41;
  MSG_MODE_TRANS_DOWNLOAD_START   = 42;
  MSG_MODE_TRANS_DOWNLOAD_END     = 43;
  MSG_MODE_SHOW_READY_TO_TURN     = 44;
  MSG_MODE_SHARED_FOLDER_STATUS   = 45;
  MSG_MODE_DISPLAY_CH_STATUS      = 46;  //2018-12-03
    CH_STATUS_OK      = 0; //#TStatusType
    CH_STATUS_NG      = 1;
    CH_STATUS_INFO    = 2;
    CH_STATUS_IDLE    = 3;
    CH_STATUS_READY   = 4;
    CH_STATUS_ALREADY = 5;
  	{$IFDEF SUPPORT_1CG2PANEL}
    CH_STATUS_SKIP    = 6;
    {$ENDIF}

  MSG_MODE_JIG_TT_START           = 47;  //2019-01-02
  MSG_MODE_JIG_TT_STOP            = 48;  //2019-01-02
{$IFDEF REF_ISPD_A}   //2019-02-xx DFS_FTP
  MSG_MODE_LOG_OUT_GUI            = 49;
  MSG_MODE_DOWNLOAD_DFT           = 50;
  MSG_MODE_UPLOAD_DFT             = 51;
{$ENDIF}
  MSG_MODE_CONFIRM_HOST           = 52;
  MSG_MODE_STOP_CAMERA            = 53;
  MSG_MODE_RESET_TOWERLAMP        = 54;
  MSG_MODE_DIO_LOG                = 55; //2023-05-02 DioLog
  //.....
  MSG_MODE_OTHERCH_SCANBCR_MSG    = 91;   //2023-08-11
    OTHERCH_SCANBCR_VISIBLE_OFF = 0;
    OTHERCH_SCANBCR_VISIBLE_ON  = 1;

	{$IFDEF SUPPORT_1CG2PANEL}
  MSG_MODE_ALLCH_SKIP_POCB        = 92;   //2022-06-08
  MSG_MODE_CONFIRM_SKIP_POCB      = 93;   //2022-06-08
	{$ENDIF}
  MSG_MODE_IONIZER_ONOFF          = 94;   //2022-01-02
  MSG_MODE_DISPLAY_CAM_CRC        = 95;
  MSG_MODE_DISPLAY_FLASH_WRITE    = 96;   //2021-05-21
      FLASH_PROGRESS_NONE             = 0; //2021-05
      FLASH_PROGRESS_START            = 1; //2021-05
      FLASH_PROGRESS_ERASE_START      = 2; //2021-05
      FLASH_PROGRESS_ERASE_END        = 3; //2021-05
      FLASH_PROGRESS_DATA_PERCENTAGE  = 4; //2021-05
      FLASH_PROGRESS_ENDACK_START     = 5; //2021-05
      FLASH_PROGRESS_ENDACK_END       = 6; //2021-05
  MSG_MODE_DISPLAY_FLOW_SEQ       = 97;   //2019-05-20
  MSG_MODE_SEND_CAM_TSTOP         = 98;   //2018-12-12
  MSG_MODE_DISPLAY_JIG_STATUS     = 99;   //2018-12-10

  MSG_MODE_MOTION_CONNECT         = 100;  //TBD:MOTION? GUI?
  MSG_MODE_MOTION_INIT            = (MSG_MODE_MOTION_CONNECT+1);
  MSG_MODE_MOTION_RESET           = (MSG_MODE_MOTION_CONNECT+2);
//MSG_MODE_MOTION_HOME            = (MSG_MODE_MOTION_CONNECT+3);
  MSG_MODE_MOTION_MODEL_POS       = (MSG_MODE_MOTION_CONNECT+4);
  MSG_MODE_MOTION_MOVE_START      = (MSG_MODE_MOTION_CONNECT+5);
  MSG_MODE_MOTION_MOVE_STOP       = (MSG_MODE_MOTION_CONNECT+6);
  MSG_MODE_MOTION_MOVE_TO_HOME    = (MSG_MODE_MOTION_CONNECT+7);
  MSG_MODE_MOTION_MOVE_TO_LIMIT   = (MSG_MODE_MOTION_CONNECT+8);
  MSG_MODE_MOTION_MOVE_TO_POS     = (MSG_MODE_MOTION_CONNECT+9);
  MSG_MODE_MOTION_MOVE_ABS        = (MSG_MODE_MOTION_CONNECT+10);
  MSG_MODE_MOTION_MOVE_INC        = (MSG_MODE_MOTION_CONNECT+11);
  MSG_MODE_MOTION_MOVE_JOG        = (MSG_MODE_MOTION_CONNECT+12);
  MSG_MODE_MOTION_MOVE_FORWARD    = (MSG_MODE_MOTION_CONNECT+13);
  MSG_MODE_MOTION_MOVE_BACKWARD   = (MSG_MODE_MOTION_CONNECT+14);
  MSG_MODE_MOTION_SERVO_ON        = (MSG_MODE_MOTION_CONNECT+15);
  MSG_MODE_MOTION_SERVO_OFF       = (MSG_MODE_MOTION_CONNECT+16);
  MSG_MODE_MOTION_GET_ACT_POS     = (MSG_MODE_MOTION_CONNECT+17);
  MSG_MODE_MOTION_SET_ACT_POS     = (MSG_MODE_MOTION_CONNECT+18);
  MSG_MODE_MOTION_GET_CMD_POS     = (MSG_MODE_MOTION_CONNECT+19);
  MSG_MODE_MOTION_SET_CMD_POS     = (MSG_MODE_MOTION_CONNECT+20);
  {$IFDEF HAS_MOTION_TILTING}
  MSG_MODE_MOTION_MOVE_TILTUP     = (MSG_MODE_MOTION_CONNECT+21); //F2CH
  MSG_MODE_MOTION_MOVE_TILTDOWN   = (MSG_MODE_MOTION_CONNECT+22); //F2CH
  {$ENDIF}
  {$IFDEF SUPPORT_1CG2PANEL}
  MSG_MODE_MOTION_SYNCMODE_SET    = (MSG_MODE_MOTION_CONNECT+23); //A2CHv3:MOTION:SYNC-MOVE
  MSG_MODE_MOTION_SYNCMODE_RESET  = (MSG_MODE_MOTION_CONNECT+24); //A2CHv3:MOTION:SYNC-MOVE
  MSG_MODE_MOTION_SYNCMODE_GET    = (MSG_MODE_MOTION_CONNECT+25); //A2CHv3:MOTION:SYNC-MOVE
  {$ENDIF}

  {$IFDEF HAS_ROBOT_CAM_Z}
  MSG_MODE_ROBOT_CONNECT_MODBUS  = 150;                                //A2CHv3:ROBOT
  MSG_MODE_ROBOT_CONNECT_COMMAND = (MSG_MODE_ROBOT_CONNECT_MODBUS+1);  //A2CHv3:ROBOT
//MSG_MODE_ROBOT_INIT            = (MSG_MODE_ROBOT_CONNECT_MODBUS+2);  //A2CHv3:ROBOT
//MSG_MODE_ROBOT_RESET           = (MSG_MODE_ROBOT_CONNECT_MODBUS+3);  //A2CHv3:ROBOT
  MSG_MODE_ROBOT_HOME_COORD      = (MSG_MODE_ROBOT_CONNECT_MODBUS+4);  //A2CHv3:ROBOT
  MSG_MODE_ROBOT_MODEL_COORD     = (MSG_MODE_ROBOT_CONNECT_MODBUS+5);  //A2CHv3:ROBOT
  MSG_MODE_ROBOT_STANDBY_COORD   = (MSG_MODE_ROBOT_CONNECT_MODBUS+6);  //A2CHv3:ROBOT
  MSG_MODE_ROBOT_MOVE_TO_HOME    = (MSG_MODE_ROBOT_CONNECT_MODBUS+7);  //A2CHv3:ROBOT
  MSG_MODE_ROBOT_MOVE_TO_MODEL   = (MSG_MODE_ROBOT_CONNECT_MODBUS+8);  //A2CHv3:ROBOT
  MSG_MODE_ROBOT_MOVE_TO_STANDBY = (MSG_MODE_ROBOT_CONNECT_MODBUS+9);  //A2CHv3:ROBOT
  MSG_MODE_ROBOT_MOVE_START      = (MSG_MODE_ROBOT_CONNECT_MODBUS+10); //A2CHv3:ROBOT
  MSG_MODE_ROBOT_MOVE_STOP       = (MSG_MODE_ROBOT_CONNECT_MODBUS+11); //A2CHv3:ROBOT
  MSG_MODE_ROBOT_MOVE_REL        = (MSG_MODE_ROBOT_CONNECT_MODBUS+12); //A2CHv3:ROBOT
  MSG_MODE_ROBOT_MOVE_JOG        = (MSG_MODE_ROBOT_CONNECT_MODBUS+13); //A2CHv3:ROBOT
  MSG_MODE_ROBOT_GET_STATUS      = (MSG_MODE_ROBOT_CONNECT_MODBUS+14); //A2CHv3:ROBOT
  MSG_MODE_ROBOT_GET_COORD       = (MSG_MODE_ROBOT_CONNECT_MODBUS+15); //A2CHv3:ROBOT
  {$ENDIF} //HAS_ROBOT_CAM_Z

  //============================================================================
  //
  //============================================================================

	//TBD? ERROR CODE?
	ERR_OK				              = 0;       //TBD:A2CH? ErrCode? GUI?
	ERR_DIO_CONNECT          		= 1;
  //
	ERR_MOTION_CONNECT	        = 10;
	ERR_MOTION_INIT	            = (ERR_MOTION_CONNECT+1);
	ERR_MOTION_NOT_CONNECTED    = (ERR_MOTION_CONNECT+2);
	ERR_MOTION_RESET            = (ERR_MOTION_CONNECT+3);
  ERR_MOTION_MOVE_START       = (ERR_MOTION_CONNECT+4);
  ERR_MOTION_MOVE_STOP        = (ERR_MOTION_CONNECT+5);
  ERR_MOTION_MOVE_TO_HOME     = (ERR_MOTION_CONNECT+6);
  ERR_MOTION_MOVE_TO_LIMIT    = (ERR_MOTION_CONNECT+7);
  ERR_MOTION_MOVE_TO_POS      = (ERR_MOTION_CONNECT+8);
  ERR_MOTION_MOVE_ABS         = (ERR_MOTION_CONNECT+9);
  ERR_MOTION_MOVE_DEC         = (ERR_MOTION_CONNECT+10);
  ERR_MOTION_MOVE_INC         = (ERR_MOTION_CONNECT+11);
  ERR_MOTION_MOVE_JOG         = (ERR_MOTION_CONNECT+12);
  ERR_MOTION_MOVE_FORWARD     = (ERR_MOTION_CONNECT+13);
  ERR_MOTION_MOVE_BACKWARD    = (ERR_MOTION_CONNECT+14);
  ERR_MOTION_SERVO_OFF        = (ERR_MOTION_CONNECT+15);
	ERR_MOTION_SERVO_ON         = (ERR_MOTION_CONNECT+16);
  ERR_MOTION_GET_CMD_POS      = (ERR_MOTION_CONNECT+17);
  ERR_MOTION_GET_ACT_POS      = (ERR_MOTION_CONNECT+18);
  ERR_MOTION_SET_CMD_POS      = (ERR_MOTION_CONNECT+19);
  ERR_MOTION_SET_ACT_POS      = (ERR_MOTION_CONNECT+20);
  ERR_MOTION_ALARM_ON         = (ERR_MOTION_CONNECT+21);
//ERR_MOTION_MOVE_START_OK    = (ERR_MOTION_CONNECT+22);
//ERR_MOTION_MOVE_STOP_OK     = (ERR_MOTION_CONNECT+23);
  ERR_MOTION_HOME             = (ERR_MOTION_CONNECT+24);
  ERR_MOTION_MODEL_POS        = (ERR_MOTION_CONNECT+25);
  {$IFDEF HAS_MOTION_TILTING}
  ERR_MOTION_MOVE_TILTUP      = (ERR_MOTION_CONNECT+26);   //F2CH
  ERR_MOTION_MOVE_TILTDOWN    = (ERR_MOTION_CONNECT+27);   //F2CH
  {$ENDIF}
  {$IFDEF SUPPORT_1CG2PANEL}
  ERR_MOTION_SYNCMODE_SET     = (ERR_MOTION_CONNECT+26);   //A2CHv3:MOTION:SYNC-MOVE
  ERR_MOTION_SYNCMODE_RESET   = (ERR_MOTION_CONNECT+27);   //A2CHv3:MOTION:SYNC-MOVE
  ERR_MOTION_SYNCMODE_GET     = (ERR_MOTION_CONNECT+28);   //A2CHv3:MOTION:SYNC-MOVE
  {$ENDIF}
  //
  {$IFDEF HAS_ROBOT_CAM_Z}
  ERR_ROBOT_CONNECT              = ERR_MOTION_CONNECT + 30;  //A2CHv3:ROBOT
  ERR_ROBOT_INIT                 = (ERR_ROBOT_CONNECT+1);    //A2CHv3:ROBOT
  ERR_ROBOT_MODBUS_DISCONNECTED  = (ERR_ROBOT_CONNECT+2);    //A2CHv3:ROBOT
  ERR_ROBOT_COMMAND_DISCONNECTED = (ERR_ROBOT_CONNECT+3);    //A2CHv3:ROBOT
  ERR_ROBOT_MOVE_TO_HOME         = (ERR_ROBOT_CONNECT+4);    //A2CHv3:ROBOT
  ERR_ROBOT_MOVE_TO_MODEL        = (ERR_ROBOT_CONNECT+5);    //A2CHv3:ROBOT
  ERR_ROBOT_MOVE_TO_STANDBY      = (ERR_ROBOT_CONNECT+6);    //A2CHv3:ROBOT
  ERR_ROBOT_MOVE_JOG             = (ERR_ROBOT_CONNECT+7);    //A2CHv3:ROBOT
  ERR_ROBOT_MOVE_REL             = (ERR_ROBOT_CONNECT+8);    //A2CHv3:ROBOT
  ERR_ROBOT_SEND_TCP_CMD         = (ERR_ROBOT_CONNECT+9);    //A2CHv3:ROBOT
  ERR_ROBOT_GET_STATUS           = (ERR_ROBOT_CONNECT+10);   //A2CHv3:ROBOT
  ERR_ROBOT_GET_COORD            = (ERR_ROBOT_CONNECT+11);   //A2CHv3:ROBOT
  ERR_ROBOT_ALARM_ON             = (ERR_ROBOT_CONNECT+12);   //A2CHv3:ROBOT
  ERR_ROBOT_MOVE_START_OK        = (ERR_ROBOT_CONNECT+13);   //A2CHv3:ROBOT
  ERR_ROBOT_CUR_COORD            = (ERR_ROBOT_CONNECT+14);   //A2CHv3:ROBOT (neither HOME nor MODEL)
  {$ENDIF}

  //============================================================================
  //
  //============================================================================

 	//----------------------------------------------------------------------------
  ALARM_CLASS_NONE            = 0;  // No Alarm
  ALARM_CLASS_SAFETY          = 1;
  ALARM_CLASS_SERIOUS         = 2;
  ALARM_CLASS_LIGHT           = 3;

 	//----------------------------------------------------------------------------
{$IF Defined(POCB_A2CH)} //############################################
  ALARM_RESERVED0                       = 0;  //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_NOT_CONNECTED               = 1;  //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_EMO                         = 2;  //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_TEACH_MODE_SWITCH           = 3;  //A2CH|----|------|------
  ALARM_DIO_LIGHT_CURTAIN               = 4;  //A2CH|----|------|------
  ALARM_DIO_DOOR_LEFT                   = 5;  //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_DOOR_RIGHT                  = 6;  //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_DOOR_UNDER                  = 7;  //A2CH|----|------|------
  ALARM_DIO_LEFT_FAN_IN                 = 8;  //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_RIGHT_FAN_IN                = 9;  //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_LEFT_FAN_OUT                = 10; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_RIGHT_FAN_OUT               = 11; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_TEMPERATURE                 = 12; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_POWER_HIGH						      = 13; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_MAIN_REGULATOR				      = 14; //A2CH|----|------|------
  ALARM_DIO_MC1                         = 15; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_MC2                         = 16; //A2CH|F2CH|A2CHv2|A2CHv3

  ALARM_DIO_FIRST = ALARM_DIO_EMO;
  ALARM_DIO_LAST  = ALARM_DIO_MC2;

  ALARM_HANDBCR_NOT_CONNECTED						= 17; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_SWITCHBUTTON1_NOT_CONNECTED			= 18; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_SWITCHBUTTON2_NOT_CONNECTED			= 19; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_SHARED_FOLDER_NOT_EXIST					= 20; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CAMERA_PC1_DISCONNECTED					= 21; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CAMERA_PC2_DISCONNECTED					= 22; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_MES_HOST_DISCONNECTED						= 23; //A2CH|F2CH|A2CHv2|A2CHv3

  ALARM_CH1_PG_DISCONNECTED							= 24; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH2_PG_DISCONNECTED							= 25; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH1_SPI_DISCONNECTED						= 26; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH2_SPI_DISCONNECTED						= 27; //A2CH|F2CH|A2CHv2|A2CHv3

  ALARM_CH1_MOTION_Y_DISCONNECTED				= 28; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH1_MOTION_Y_SIG_ALARM_ON				= 29; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH1_MOTION_Y_INVALID_UNITPULSE	= 30; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH1_MOTION_Y_NEED_HOME_SEARCH   = 31; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH1_MOTION_Y_MODEL_POS_NG   		= 32; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH1_MOTION_Z_DISCONNECTED				= 33; //A2CH|F2CH|A2CHv2|------
  ALARM_CH1_MOTION_Z_SIG_ALARM_ON				= 34; //A2CH|F2CH|A2CHv2|------
  ALARM_CH1_MOTION_Z_INVALID_UNITPULSE	= 35; //A2CH|F2CH|A2CHv2|------
  ALARM_CH1_MOTION_Z_NEED_HOME_SEARCH   = 36; //A2CH|F2CH|A2CHv2|------
  ALARM_CH1_MOTION_Z_MODEL_POS_NG    		= 37; //A2CH|F2CH|A2CHv2|------
  ALARM_CH2_MOTION_Y_DISCONNECTED				= 38; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH2_MOTION_Y_SIG_ALARM_ON				= 39; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH2_MOTION_Y_INVALID_UNITPULSE	= 40; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH2_MOTION_Y_NEED_HOME_SEARCH   = 41; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH2_MOTION_Y_MODEL_POS_NG   		= 42; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH2_MOTION_Z_DISCONNECTED				= 43; //A2CH|F2CH|A2CHv2|------
  ALARM_CH2_MOTION_Z_SIG_ALARM_ON				= 44; //A2CH|F2CH|A2CHv2|------
  ALARM_CH2_MOTION_Z_INVALID_UNITPULSE	= 45; //A2CH|F2CH|A2CHv2|------
  ALARM_CH2_MOTION_Z_NEED_HOME_SEARCH   = 46; //A2CH|F2CH|A2CHv2|------
  ALARM_CH2_MOTION_Z_MODEL_POS_NG		    = 47; //A2CH|F2CH|A2CHv2|------

  ALARM_CH1_PG_VERSION_MISMATCH			 	  = 48; //A2CH|F2CH|A2CHv2|A2CHv3 //2019-04-19 FW_VERSION
  ALARM_CH2_PG_VERSION_MISMATCH					= 49; //A2CH|F2CH|A2CHv2|A2CHv3 //2019-04-19 FW_VERSION
  ALARM_CH1_SPI_VERSION_MISMATCH				= 50; //A2CH|F2CH|A2CHv2|A2CHv3 //2019-04-19 FW_VERSION
  ALARM_CH2_SPI_VERSION_MISMATCH				= 51; //A2CH|F2CH|A2CHv2|A2CHv3 //2019-04-19 FW_VERSION

  ALARM_EXLIGHT_NOT_CONNECTED			      = 52; //A2CH|F2CH|A2CHv2|A2CHv3 //2019-04-17 ExLight
  ALARM_EFU_NOT_CONNECTED			          = 53; //A2CH|F2CH|A2CHv2|A2CHv3 //2019-05-04 EFU
  ALARM_CH1_EFU_STATUS_NG	              = 54; //A2CH|----|A2CHv2|A2CHv3 //2019-05-04 EFU
  ALARM_CH2_EFU_STATUS_NG			          = 55; //A2CH|----|A2CHv2|A2CHv3 //2019-05-04 EFU
  ALARM_CH1_IONIZER_NOT_CONNECTED       = 56; //A2CH|----|A2CHv2|A2CHv3 //2019-08-23 Ionizer
  ALARM_CH1_IONIZER_STATUS_NG	          = 57; //A2CH|----|A2CHv2|A2CHv3 //2019-08-23 Ionizer
  ALARM_CH2_IONIZER_NOT_CONNECTED       = 58; //A2CH|----|A2CHv2|A2CHv3 //2019-08-23 Ionizer
  ALARM_CH2_IONIZER_STATUS_NG		        = 59; //A2CH|----|A2CHv2|A2CHv3 //2019-08-23 Ionizer

	ALARM_DIO_EXTRA_EMS = (ALARM_CH2_IONIZER_STATUS_NG + 1);
  MAX_ALARM_NO        = ALARM_DIO_EXTRA_EMS;

{$ELSEIF Defined(POCB_A2CHv2)}  //#####################################
  ALARM_RESERVED0									      = 0;  //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_NOT_CONNECTED					      = 1;  //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_EMO										      = 2;  //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_LEFT_SWITCH						      = 3;  //----|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_RIGHT_SWITCH 					      = 4;  //----|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_STAGE1_LIGHT_CURTAIN	      = 5;  //----|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_STAGE2_LIGHT_CURTAIN	      = 6;  //----|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_DOOR_LEFT							      = 7;  //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_DOOR_RIGHT						      = 8;  //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_DOOR_UNDER_LEFT1			      = 9;  //----|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_DOOR_UNDER_LEFT2			      = 10; //----|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_DOOR_UNDER_RIGHT1			      = 11; //----|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_DOOR_UNDER_RIGHT2			      = 12; //----|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_LEFT_FAN_IN						      = 13; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_RIGHT_FAN_IN					      = 14; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_LEFT_FAN_OUT					      = 15; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_RIGHT_FAN_OUT					      = 16; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_TEMPERATURE						      = 17; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_POWER_HIGH						      = 18; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_CYLINDER_REGULATOR		      = 19; //----|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_VACUUM_REGULATOR			      = 20; //----|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_MC1				                  = 21; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_DIO_MC2				                  = 22; //A2CH|F2CH|A2CHv2|A2CHv3

  ALARM_DIO_FIRST = ALARM_DIO_EMO;
  ALARM_DIO_LAST  = ALARM_DIO_MC2;

  ALARM_HANDBCR_NOT_CONNECTED			      = 23; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_SWITCHBUTTON1_NOT_CONNECTED			= 24; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_SWITCHBUTTON2_NOT_CONNECTED			= 25; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_SHARED_FOLDER_NOT_EXIST					= 26; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CAMERA_PC1_DISCONNECTED					= 27; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CAMERA_PC2_DISCONNECTED					= 28; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_MES_HOST_DISCONNECTED						= 29; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH1_PG_DISCONNECTED							= 30; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH2_PG_DISCONNECTED							= 31; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH1_SPI_DISCONNECTED						= 32; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH2_SPI_DISCONNECTED						= 33; //A2CH|F2CH|A2CHv2|A2CHv3

  ALARM_CH1_MOTION_Y_DISCONNECTED				= 34; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH1_MOTION_Y_SIG_ALARM_ON				= 35; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH1_MOTION_Y_INVALID_UNITPULSE	= 36; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH1_MOTION_Y_NEED_HOME_SEARCH   = 37; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH1_MOTION_Y_MODEL_POS_NG   		= 38; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH1_MOTION_Z_DISCONNECTED				= 39; //A2CH|F2CH|A2CHv2|------
  ALARM_CH1_MOTION_Z_SIG_ALARM_ON				= 40; //A2CH|F2CH|A2CHv2|------
  ALARM_CH1_MOTION_Z_INVALID_UNITPULSE	= 41; //A2CH|F2CH|A2CHv2|------
  ALARM_CH1_MOTION_Z_NEED_HOME_SEARCH   = 42; //A2CH|F2CH|A2CHv2|------
  ALARM_CH1_MOTION_Z_MODEL_POS_NG    		= 43; //A2CH|F2CH|A2CHv2|------
  ALARM_CH2_MOTION_Y_DISCONNECTED				= 44; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH2_MOTION_Y_SIG_ALARM_ON				= 45; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH2_MOTION_Y_INVALID_UNITPULSE	= 46; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH2_MOTION_Y_NEED_HOME_SEARCH   = 47; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH2_MOTION_Y_MODEL_POS_NG   		= 48; //A2CH|F2CH|A2CHv2|A2CHv3
  ALARM_CH2_MOTION_Z_DISCONNECTED				= 49; //A2CH|F2CH|A2CHv2|------
  ALARM_CH2_MOTION_Z_SIG_ALARM_ON				= 50; //A2CH|F2CH|A2CHv2|------
  ALARM_CH2_MOTION_Z_INVALID_UNITPULSE	= 51; //A2CH|F2CH|A2CHv2|------
  ALARM_CH2_MOTION_Z_NEED_HOME_SEARCH   = 52; //A2CH|F2CH|A2CHv2|------
  ALARM_CH2_MOTION_Z_MODEL_POS_NG		    = 53; //A2CH|F2CH|A2CHv2|------
  ALARM_CH1_MOTION_T_DISCONNECTED				= 54; //----|F2CH|------|------
  ALARM_CH1_MOTION_T_SIG_ALARM_ON				= 55; //----|F2CH|------|------
  ALARM_CH1_MOTION_T_INVALID_UNITPULSE	= 56; //----|F2CH|------|------
  ALARM_CH1_MOTION_T_NEED_HOME_SEARCH   = 57; //----|F2CH|------|------
  ALARM_CH1_MOTION_T_MODEL_POS_NG    		= 58; //----|F2CH|------|------
  ALARM_CH2_MOTION_T_DISCONNECTED				= 59; //----|F2CH|------|------
  ALARM_CH2_MOTION_T_SIG_ALARM_ON				= 60; //----|F2CH|------|------
  ALARM_CH2_MOTION_T_INVALID_UNITPULSE	= 61; //----|F2CH|------|------
  ALARM_CH2_MOTION_T_NEED_HOME_SEARCH   = 62; //----|F2CH|------|------
  ALARM_CH2_MOTION_T_MODEL_POS_NG    		= 63; //----|F2CH|------|------

  ALARM_CH1_PG_VERSION_MISMATCH			 	  = 64; //A2CH|F2CH|A2CHv2|A2CHv3 //2019-04-19 FW_VERSION
  ALARM_CH2_PG_VERSION_MISMATCH					= 65; //A2CH|F2CH|A2CHv2|A2CHv3 //2019-04-19 FW_VERSION
  ALARM_CH1_SPI_VERSION_MISMATCH				= 66; //A2CH|F2CH|A2CHv2|A2CHv3 //2019-04-19 FW_VERSION
  ALARM_CH2_SPI_VERSION_MISMATCH				= 67; //A2CH|F2CH|A2CHv2|A2CHv3 //2019-04-19 FW_VERSION

  ALARM_EXLIGHT_NOT_CONNECTED			      = 68; //A2CH|F2CH|A2CHv2|A2CHv3 //2019-04-17 ExLight
  ALARM_EFU_NOT_CONNECTED			          = 69; //A2CH|----|A2CHv2|A2CHv3 //2019-05-04 EFU
  ALARM_CH1_EFU_STATUS_NG	              = 70; //A2CH|----|A2CHv2|A2CHv3 //2019-05-04 EFU
  ALARM_CH2_EFU_STATUS_NG	              = 71; //A2CH|----|A2CHv2|A2CHv3 //2019-05-04 EFU
  ALARM_CH1_IONIZER_NOT_CONNECTED       = 72; //A2CH|----|A2CHv2|A2CHv3 //2019-08-23 Ionizer
  ALARM_CH1_IONIZER_STATUS_NG           = 73; //A2CH|----|A2CHv2|A2CHv3 //2019-08-23 Ionizer
  ALARM_CH2_IONIZER_NOT_CONNECTED       = 74; //A2CH|----|A2CHv2|A2CHv3 //2019-08-23 Ionizer
  ALARM_CH2_IONIZER_STATUS_NG	          = 75; //A2CH|----|A2CHv2|A2CHv3 //2019-08-23 Ionizer

	ALARM_DIO_EXTRA_EMS = (ALARM_CH2_IONIZER_STATUS_NG + 1);
  MAX_ALARM_NO        = ALARM_DIO_EXTRA_EMS;

{$ELSEIF Defined(POCB_A2CHv3) or Defined(POCB_A2CHv4) or Defined(POCB_ATO) or Defined(POCB_GAGO)}  //####################
  ALARM_RESERVED0                       = 0;  //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_DIO_NOT_CONNECTED               = 1;  //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_DIO_EMO1_FRONT                  = 2;  //----|----|------|A2CHv3|A2CHv4
  ALARM_DIO_EMO2_RIGHT                  = 3;  //----|----|------|A2CHv3|A2CHv4
  ALARM_DIO_EMO3_INNER_RIGHT            = 4;  //----|----|------|A2CHv3|A2CHv4
  ALARM_DIO_EMO4_INNER_LEFT             = 5;  //----|----|------|A2CHv3|A2CHv4
  ALARM_DIO_EMO5_LEFT                   = 6;  //----|----|------|A2CHv3|A2CHv4
  ALARM_DIO_LEFT_FAN_IN                 = 7;  //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_DIO_RIGHT_FAN_IN                = 8;  //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_DIO_LEFT_FAN_OUT                = 9;  //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_DIO_RIGHT_FAN_OUT               = 10; //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_DIO_STAGE1_LIGHT_CURTAIN        = 11; //----|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_DIO_STAGE2_LIGHT_CURTAIN        = 12; //----|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_DIO_STAGE1_NOT_AUTOMODE         = 13; //----|----|------|A2CHv3|A2CHv4
//ALARM_DIO_STAGE1_TEACHMODE            = 14; //----|----|------|A2CHv3|A2CHv4
  ALARM_DIO_STAGE2_NOT_AUTOMODE         = 15; //----|----|------|A2CHv3|A2CHv4
//ALARM_DIO_STAGE2_TEACHMODE            = 16; //----|----|------|A2CHv3|A2CHv4
  ALARM_DIO_STAGE1_DOOR1_OPEN           = 17; //----|----|------|A2CHv3|A2CHv4
  ALARM_DIO_STAGE1_DOOR2_OPEN           = 18; //----|----|------|A2CHv3|A2CHv4
  ALARM_DIO_STAGE2_DOOR1_OPEN           = 19; //----|----|------|A2CHv3|A2CHv4
  ALARM_DIO_STAGE2_DOOR2_OPEN           = 20; //----|----|------|A2CHv3|A2CHv4
  ALARM_DIO_CYLINDER_REGULATOR          = 21; //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_DIO_VACUUM_REGULATOR            = 22; //----|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_DIO_TEMPERATURE                 = 23; //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_DIO_POWER_HIGH                  = 24; //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_DIO_MC1                         = 25; //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_DIO_MC2                         = 26; //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4

	{$IFDEF HAS_DIO_FAN_INOUT_PC} //2022-07-15 A2CHv4_#3(FanInOutPC)
  ALARM_DIO_MAINPC_FAN_IN               = 27; //----|----|------|------|A2CHv4_#3
  ALARM_DIO_MAINPC_FAN_OUT              = 28; //----|----|------|------|A2CHv4_#3
  ALARM_DIO_CAMPC_FAN_IN                = 29; //----|----|------|------|A2CHv4_#3
  ALARM_DIO_CAMPC_FAN_OUT               = 30; //----|----|------|------|A2CHv4_#3
	{$ENDIF}

	{$IFDEF HAS_DIO_IN_DOOR_LOCK} //2023-12-07
  ALARM_DIO_STAGE1_DOOR1_LOCK           = 31;
  ALARM_DIO_STAGE1_DOOR2_LOCK           = 32;
  ALARM_DIO_STAGE2_DOOR1_LOCK           = 33;
  ALARM_DIO_STAGE2_DOOR2_LOCK           = 34;
  {$ENDIF}
	{$IFDEF HAS_DIO_Y_AXIS_MC} //2023-12-07
  ALARM_DIO_Y_AXIS_MC_CH1               = 35;
  ALARM_DIO_Y_AXIS_MC_CH2               = 36;
  {$ENDIF}
  ALARM_DIO_CP1                         = 37;
  ALARM_DIO_CP2                         = 38;
  ALARM_DIO_CP3                         = 39;
  ALARM_DIO_CP6                         = 40;

  {$IFDEF SUPPORT_1CG2PANEL} //A2CHv3
  ALARM_DIO_LOADZONE_PARTITION_NOT_DETECTED = 50; //----|----|------|A2CHv3|------
  ALARM_DIO_SHUTTER_GUIDE_NOT_UP            = 51; //----|----|------|A2CHv3|------ // CP_POCB|CP-GIB_POCB
  ALARM_DIO_CAMZONE_PARTITION_NOT_DOWN      = 52; //----|----|------|A2CHv3|------ // CP_POCB|CP-GIB_POCB
  ALARM_DIO_CAMZONE_INNER_DOOR_NOT_CLOSE    = 53; //----|----|------|A2CHv3|------ // CP_POCB|CP-GIB_POCB
  ALARM_DIO_ASSY_JIG_DETECTED               = 54; //----|----|------|A2CHv3|------ // CP_POCB|CP-GIB_POCB
  ALARM_DIO_SHUTTER_GUIDE_NOT_DOWN          = 55; //----|----|------|A2CHv3|------ // ASSY_POCB
  ALARM_DIO_CAMZONE_PARTITION_NOT_UP        = 56; //----|----|------|A2CHv3|------ // ASSY_POCB
  ALARM_DIO_CAMZONE_INNER_DOOR_NOT_OPEN     = 57; //----|----|------|A2CHv3|------ // ASSY_POCB
  ALARM_DIO_LOADZONE_PARTITION_DETECTED     = 58; //----|----|------|A2CHv3|------ // ASSY_POCB
  ALARM_DIO_ASSY_JIG_STAGE_NOT_ALIGNED      = 59; //----|----|------|A2CHv3|------ // ASSY_POCB
  {$ENDIF}

  ALARM_DIO_FIRST = ALARM_DIO_EMO1_FRONT;
{$IFDEF SUPPORT_1CG2PANEL} //A2CHv3
  ALARM_DIO_LAST  = ALARM_DIO_ASSY_JIG_STAGE_NOT_ALIGNED;
{$ELSE}
  {$IFDEF HAS_DIO_Y_AXIS_MC}
    ALARM_DIO_LAST  = ALARM_DIO_Y_AXIS_MC_CH2;
  {$ELSE}
    {$IFDEF HAS_DIO_IN_DOOR_LOCK}
    ALARM_DIO_LAST  = ALARM_DIO_STAGE2_DOOR2_LOCK;
    {$ELSE}
  		{$IFDEF HAS_DIO_FAN_INOUT_PC}  //2022-07-15 A2CHv4_#3(FanInOutPC)
  	  ALARM_DIO_LAST  = ALARM_DIO_CAMPC_FAN_OUT;
  		{$ELSE}
  	  ALARM_DIO_LAST  = ALARM_DIO_MC2;
  		{$ENDIF}
    {$ENDIF}
  {$ENDIF}
{$ENDIF}

  ALARM_CH1_PG_DISCONNECTED             = 100;  //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH2_PG_DISCONNECTED             = 101;  //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH1_PG_VERSION_MISMATCH         = 102;  //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH2_PG_VERSION_MISMATCH         = 103;  //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH1_SPI_DISCONNECTED            = 104;  //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH2_SPI_DISCONNECTED            = 105;  //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH1_SPI_VERSION_MISMATCH        = 106;  //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH2_SPI_VERSION_MISMATCH        = 107;  //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4

  ALARM_CAMERA_PC1_DISCONNECTED         = 120;  //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_CAMERA_PC2_DISCONNECTED         = 121;  //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_HANDBCR_NOT_CONNECTED           = 122;  //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_SWITCHBUTTON1_NOT_CONNECTED     = 123;  //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_SWITCHBUTTON2_NOT_CONNECTED     = 124;  //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_SHARED_FOLDER_NOT_EXIST         = 125;  //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_MES_HOST_DISCONNECTED           = 126;  //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4

  ALARM_EXLIGHT_NOT_CONNECTED           = 140;  //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_EFU_NOT_CONNECTED               = 141;  //A2CH|----|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH1_EFU_STATUS_NG               = 142;  //A2CH|----|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH1_EFU2_STATUS_NG              = 143;  //----|----|------|------|A2CHv4
  ALARM_CH2_EFU_STATUS_NG               = 144;  //A2CH|----|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH2_EFU2_STATUS_NG              = 145;  //----|----|------|------|A2CHv4
  ALARM_CH1_IONIZER_NOT_CONNECTED       = 146;  //A2CH|----|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH1_IONIZER2_NOT_CONNECTED      = 147;  //----|----|------|------|A2CHv4
  ALARM_CH2_IONIZER_NOT_CONNECTED       = 148;  //A2CH|----|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH2_IONIZER2_NOT_CONNECTED      = 149;  //----|----|------|------|A2CHv4
  ALARM_CH1_IONIZER_STATUS_NG           = 150;  //A2CH|----|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH1_IONIZER2_STATUS_NG          = 151;  //----|----|------|------|A2CHv4
  ALARM_CH2_IONIZER_STATUS_NG           = 152;  //A2CH|----|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH2_IONIZER2_STATUS_NG          = 153;  //----|----|------|------|A2CHv4

  ALARM_CH1_MOTION_Y_DISCONNECTED       = 160; //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH1_MOTION_Y_SIG_ALARM_ON       = 161; //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH1_MOTION_Y_INVALID_UNITPULSE  = 162; //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH1_MOTION_Y_NEED_HOME_SEARCH   = 163; //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH1_MOTION_Y_MODEL_POS_NG       = 164; //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH2_MOTION_Y_DISCONNECTED       = 165; //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH2_MOTION_Y_SIG_ALARM_ON       = 166; //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH2_MOTION_Y_INVALID_UNITPULSE  = 167; //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH2_MOTION_Y_NEED_HOME_SEARCH   = 168; //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4
  ALARM_CH2_MOTION_Y_MODEL_POS_NG       = 169; //A2CH|F2CH|A2CHv2|A2CHv3|A2CHv4

  ALARM_CH1_ROBOT_MODBUS_DISCONNECTED   = 200; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH1_ROBOT_COMMAND_DISCONNECTED  = 201; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH1_ROBOT_FATAL_ERROR           = 202; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH1_ROBOT_PROJECT_NOT_RUNNING   = 203; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH1_ROBOT_PROJECT_EDITING       = 204; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH1_ROBOT_PROJECT_PAUSE         = 205; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH1_ROBOT_GET_CONTROL           = 206; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH1_ROBOT_ESTOP                 = 207; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH1_ROBOT_CURR_COORD_NG         = 208; //----|----|------|A2CHv3|A2CHv4 (neither HOME nor MODEL)
  ALARM_CH1_ROBOT_NOT_AUTOMODE          = 209; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH1_ROBOT_CANNOT_MOVE           = 210; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH1_ROBOT_HOME_COORD_MISMATCH   = 211; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH1_ROBOT_MODEL_COORD_MISMATCH  = 212; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH1_ROBOT_STANDBY_COORD_MISMATCH= 213; //----|----|------|A2CHv3|A2CHv4

  ALARM_CH2_ROBOT_MODBUS_DISCONNECTED   = 220; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH2_ROBOT_COMMAND_DISCONNECTED  = 221; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH2_ROBOT_FATAL_ERROR           = 222; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH2_ROBOT_PROJECT_NOT_RUNNING   = 223; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH2_ROBOT_PROJECT_EDITING       = 224; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH2_ROBOT_PROJECT_PAUSE         = 225; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH2_ROBOT_GET_CONTROL           = 226; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH2_ROBOT_ESTOP                 = 227; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH2_ROBOT_CURR_COORD_NG         = 228; //----|----|------|A2CHv3|A2CHv4 (neither HOME nor MODEL)
  ALARM_CH2_ROBOT_NOT_AUTOMODE          = 229; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH2_ROBOT_CANNOT_MOVE           = 230; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH2_ROBOT_HOME_COORD_MISMATCH   = 231; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH2_ROBOT_MODEL_COORD_MISMATCH  = 232; //----|----|------|A2CHv3|A2CHv4
  ALARM_CH2_ROBOT_STANDBY_COORD_MISMATCH= 233; //----|----|------|A2CHv3|A2CHv4

	ALARM_DIO_EXTRA_EMS = (ALARM_CH2_ROBOT_STANDBY_COORD_MISMATCH + 1); //(EMO 이외의 EMS상태에 대한 처리: 예, AutoMode & DoorOpen?)  //TBD???
  MAX_ALARM_NO        = ALARM_DIO_EXTRA_EMS;
{$ENDIF}

  //############################################################################
  //###
  //### POCB FLOW SEQ
  //###
  //############################################################################

{$IF Defined(POCB_A2CH) or Defined(POCB_A2CHv2)}
  //TBD:A2CH? //TBD:A2CHv2?
{$ELSEIF Defined(POCB_A2CHv3) or Defined(POCB_A2CHv4) or Defined(POCB_ATO)}
  POCB_SEQ_UNKNOWN                    = 0;
  POCB_SEQ_SCAN_BCR                   = 1;
  POCB_SEQ_MES_PCHK                   = 2;
  POCB_SEQ_INIT_POWER_ON              = 3;  //#INIT_POWER_ON
  {$IFDEF SUPPORT_1CG2PANEL}
  POCB_SEQ_CONFIRM_SKIP_POCB          = 4;  //#CONFIRM_SKIP_POCB
  {$ENDIF}
  POCB_SEQ_INIT_CBPARA_WRITE          = 5;  //#CBPARA_BEFORE_WRITE
  POCB_SEQ_INIT_POWER_RESET           = 6;  //#INIT_POWER_RESET
  POCB_SEQ_PAT_DISP_POWERON           = 7;  //#INIT_PATTERN_DISPLAY
  POCB_SEQ_PROCMASK_BEFORE_CHECK      = 8;  //#PROCMASK_BEFORE_CHECK
  POCB_SEQ_PROCMASK_BEFORE_WRITE      = 9;  //#PROCMASK_BEFORE_WRITE
  POCB_SEQ_PRESS_START                = 10; //#PRESS_START
  POCB_SEQ_STAGE_FWD                  = 11; //#STAGE_FWD
  POCB_SEQ_CAM_PROC_CB1               = 12; //#CAMERA_PROC
  POCB_SEQ_CB1_CBDATA_RCV             = 13; //#RECEIVE_CBDATA #CBDATA_FILE_SAVE
  POCB_SEQ_CB1_CBDATA_FLASH_WRITE     = 14; //#FLASH_CBDATA_WRITE
  POCB_SEQ_CB1_CBPARA_AFTERPUC_WRITE  = 15; //#CBPARA_AFTERPUC_WRITE
  POCB_SEQ_CB1_POWER_RESET            = 16; //#POCB_POWER_OFF_ON                  //TBD:ATO?
  POCB_SEQ_CAM_PROC_CB2               = 17; //#CAMERA_PROC
  POCB_SEQ_CB2_CBDATA_RCV             = 18; //#RECEIVE_CBDATA #CBDATA_FILE_SAVE   //TBD:ATO?
  POCB_SEQ_CB2_CBDATA_FLASH_WRITE     = 19; //#FLASH_CBDATA_WRITE                 //TBD:ATO?
  POCB_SEQ_CB2_CBPARA_AFTERPUC_WRITE  = 20; //#CBPARA_AFTERPUC_WRITE              //TBD:ATO?
  POCB_SEQ_CB2_POWER_RESET            = 21; //#POCB_POWER_OFF_ON                  //TBD:ATO?
  POCB_SEQ_CAM_PROC_CB3               = 22; //#CAMERA_PROC
  POCB_SEQ_CB3_CBDATA_RCV             = 23; //#RECEIVE_CBDATA #CBDATA_FILE_SAVE
  POCB_SEQ_CB3_CBDATA_FLASH_WRITE     = 24; //#FLASH_CBDATA_WRITE
  POCB_SEQ_CB3_CBPARA_AFTERPUC_WRITE  = 25; //#CBPARA_AFTERPUC_WRITE
  POCB_SEQ_CB3_POWER_RESET            = 26; //#POCB_POWER_OFF_ON                  //TBD:ATO?
  POCB_SEQ_CAM_PROC_CB4               = 27; //#CAMERA_PROC
  POCB_SEQ_CB4_CBDATA_RCV             = 28; //#RECEIVE_CBDATA #CBDATA_FILE_SAVE   //TBD:ATO?
  POCB_SEQ_CB4_CBDATA_FLASH_WRITE     = 29; //#FLASH_CBDATA_WRITE                 //TBD:ATO?
  POCB_SEQ_CB4_CBPARA_AFTERPUC_WRITE  = 30; //#CBPARA_AFTERPUC_WRITE              //TBD:ATO?
  POCB_SEQ_CB4_POWER_RESET            = 31; //#POCB_POWER_OFF_ON                  //TBD:ATO?

  POCB_SEQ_CAM_PROC_EXTRA             = 22; //#BMP_DOWNLOAD (Uniformity Verify, PUC Image, BMP DOWNLOAD)
  POCB_SEQ_PROCMASK_AFTER_WRITE       = 23; //#PROCMASK_AFTER_WRITE               //TBD:ATO?
  POCB_SEQ_FINAL_CBPARA_WRITE         = 24; //#CBPARA_AFTER_WRITE
  POCB_SEQ_PUC_PROC_END               = 25; //TBD:GAGO:NEWFLOW?
  POCB_SEQ_PAT_DISP_VERIFY            = 26; //#POCB_DISPLAY_PATTERN
  POCB_SEQ_STAGE_BWD                  = 27; //#STAGE_BWD
  POCB_SEQ_MES_EICR                   = 28; //#MES_EICR
  POCB_SEQ_POWER_OFF                  = 29; //#POWER_OFF
{$ELSEIF Defined(POCB_GAGO) or Defined(POCB_F2CH)}
  POCB_SEQ_UNKNOWN                    = 0;
  POCB_SEQ_INIT_POWER_ON              = 1;  //#INIT_POWER_ON
  POCB_SEQ_INIT_CBPARA_WRITE          = 2;  //CBPARA_BEFORE_WRITE
  POCB_SEQ_INIT_POWER_RESET           = 3;
  POCB_SEQ_PAT_DISP_POWERON           = 4;
  POCB_SEQ_SCAN_BCR                   = 5;
  POCB_SEQ_MES_PCHK                   = 6;
  POCB_SEQ_PRESS_START                = 7;
  POCB_SEQ_STAGE_FWD                  = 8;
  POCB_SEQ_CAM_PROC_CB1               = 9;  //#CAMERA_PROC
  POCB_SEQ_CB1_CBDATA_RCV             = 10; //#RECEIVE_CBDATA
  POCB_SEQ_CB1_CBDATA_FLASH_WRITE     = 11; //#WRITE_CBATA_FLASH
  POCB_SEQ_CB1_CBPARA_FLASH_WRITE     = 12; //#POCB_CBPARA_WRITE_VERIFY
  POCB_SEQ_CB1_POWER_RESET            = 13; //#POCB_POWER_OFF_ON
  POCB_SEQ_CAM_PROC_CB2               = 14; //#CAMERA_PROC2
  POCB_SEQ_CB2_CBDATA_RCV             = 15; //#RECEIVE_CBDATA2
  POCB_SEQ_CB2_CBDATA_FLASH_WRITE     = 16; //#WRITE_CBATA_FLASH2
  POCB_SEQ_CB2_CBPARA_FLASH_WRITE     = 17; //#POCB_CBPARA_WRITE_VERIFY2
  POCB_SEQ_CB2_POWER_RESET            = 18; //#POCB_POWER_OFF_ON2

  POCB_SEQ_CAM_PROC_CB3               = 19;
  POCB_SEQ_CB3_CBDATA_RCV             = 20; //#RECEIVE_CBDATA
  POCB_SEQ_CB3_CBDATA_FLASH_WRITE     = 21; //#WRITE_CBATA_FLASH
  POCB_SEQ_CB3_CBPARA_FLASH_WRITE     = 22; //#POCB_CBPARA_WRITE_VERIFY
  POCB_SEQ_CB3_POWER_RESET            = 23; //#POCB_POWER_OFF_ON
  POCB_SEQ_CAM_PROC_CB4               = 24; //#CAMERA_PROC2
  POCB_SEQ_CB4_CBDATA_RCV             = 25; //#RECEIVE_CBDATA2
  POCB_SEQ_CB4_CBDATA_FLASH_WRITE     = 26; //#WRITE_CBATA_FLASH2
  POCB_SEQ_CB4_CBPARA_FLASH_WRITE     = 27; //#POCB_CBPARA_WRITE_VERIFY2
  POCB_SEQ_CB4_POWER_RESET            = 28; //#POCB_POWER_OFF_ON2

  POCB_SEQ_CAM_PROC_EXTRA             = 29; //#BMP_DOWNLOAD (Uniformity Verify, PUC Image, BMP DOWNLOAD)
  POCB_SEQ_PUC_PROC_END               = 30; //TBD:GAGO:NEWFLOW?
  POCB_SEQ_PAT_DISP_VERIFY            = 31; //#POCB_DISPLAY_PATTERN2
  POCB_SEQ_STAGE_BWD                  = 32; //#STAGE_BWD
  POCB_SEQ_MES_EICR                   = 33; //#MES_EICR
  POCB_SEQ_POWER_OFF                  = 34; //#POWER_OFF

{$ELSEIF Defined(ITOLED_POCB) or Defined(POCB_ITOLED)}
  POCB_SEQ_UNKNOWN            = 0;
  POCB_SEQ_INIT_POWER_ON      = 1;
  POCB_SEQ_PAT_DISP_POWERON   = 2;
  POCB_SEQ_SCAN_BCR           = 3;
  POCB_SEQ_MES_PCHK           = 4;
  POCB_SEQ_TCON_PARA_VERIFY   = 5;
  POCB_SEQ_FLASH_READ         = 6;
  POCB_SEQ_PUCPARA_TCON_WRITE = 7;
  POCB_SEQ_PRESS_START        = 8;
  POCB_SEQ_STAGE_FWD          = 9;
  POCB_SEQ_PAT_DISP_READY     = 10;
  POCB_SEQ_CAM_PROC_GAMMA     = 11;
  POCB_SEQ_CAM_PROC_POCBDATA_TX = 12; //2023-03-02 COLOR_CAMERA_FLOW
  POCB_SEQ_CAM_PROC_CB1       = 13;
  POCB_SEQ_CB1_CBDATA_RCV     = 14;
  POCB_SEQ_CB1_FLASH_WRITE    = 15;
  POCB_SEQ_CB1_POWER_RESET    = 16;
  POCB_SEQ_CAM_PROC_CB2       = 17;
  POCB_SEQ_CB2_CBDATA_RCV     = 18;
  POCB_SEQ_CB2_FLASH_WRITE    = 19;
  POCB_SEQ_CB2_POWER_RESET    = 20;
  POCB_SEQ_CAM_PROC_CB3       = 21;
  POCB_SEQ_CB3_CBDATA_RCV     = 22;
  POCB_SEQ_CB3_FLASH_WRITE    = 23;
  POCB_SEQ_CB3_POWER_RESET    = 24;
  POCB_SEQ_CAM_PROC_EXTRA     = 25;
  POCB_SEQ_CAM_PROC_END       = 26;
  POCB_SEQ_CAM_DISP_AFTER_CB  = 27;
  POCB_SEQ_STAGE_BWD          = 28;
  POCB_SEQ_MES_EICR           = 29;
  POCB_SEQ_POWER_OFF          = 30;
{$ENDIF}
  POCB_SEQ_MAX = POCB_SEQ_POWER_OFF;

  //############################################################################
  //###
  //### POCB_FC
  //###
  //############################################################################

  POCB_FC_OK                       = 0;
  POCB_FC_OPERATOR_STOP            = (POCB_FC_OK + 1);
  POCB_FC_ALARM_STOP               = (POCB_FC_OK + 2);
  POCB_FC_POWER_ON                 = (POCB_FC_OK + 3);
  POCB_FC_PATTERN_DISPLAY          = (POCB_FC_OK + 4);
  POCB_FC_PATTERN_BMP_DOWN         = (POCB_FC_OK + 5);
  POCB_FC_EEPROM_READ              = (POCB_FC_OK + 6);
  POCB_FC_EEPROM_WRITE             = (POCB_FC_OK + 7);
  POCB_FC_EEPROM_PROCMASK_VERIFY   = (POCB_FC_OK + 8);
  POCB_FC_EEPROM_CBPARA_VERIFY     = (POCB_FC_OK + 9);
  POCB_FC_TCON_READ                = (POCB_FC_OK + 10);
  POCB_FC_TCON_WRITE               = (POCB_FC_OK + 11);
  POCB_FC_TCON_PARA_VERIFY         = (POCB_FC_OK + 12);
  POCB_FC_FLASH_READ               = (POCB_FC_OK + 13);
  POCB_FC_FLASH_WRITE_CBPARA       = (POCB_FC_OK + 14);
  POCB_FC_FLASH_WRITE_CBDATA       = (POCB_FC_OK + 15);

  POCB_FC_CAM_COMM_NG              = 20;
  POCB_FC_CAM_START_CB1_TX_FAIL    = (POCB_FC_CAM_COMM_NG + 1);  //TSTART
  POCB_FC_CAM_START_CB1_NAK        = (POCB_FC_CAM_COMM_NG + 2);
  POCB_FC_CAM_START_CB1_TIMEOUT    = (POCB_FC_CAM_COMM_NG + 3);
  POCB_FC_CAM_START_CB2_TX_FAIL    = (POCB_FC_CAM_COMM_NG + 4);  //TSTART2
  POCB_FC_CAM_START_CB2_NAK        = (POCB_FC_CAM_COMM_NG + 5);
  POCB_FC_CAM_START_CB2_TIMEOUT    = (POCB_FC_CAM_COMM_NG + 6);
  POCB_FC_CAM_START_CB3_TX_FAIL    = (POCB_FC_CAM_COMM_NG + 7);  //TSTART2
  POCB_FC_CAM_START_CB3_NAK        = (POCB_FC_CAM_COMM_NG + 8);
  POCB_FC_CAM_START_CB3_TIMEOUT    = (POCB_FC_CAM_COMM_NG + 9);
  POCB_FC_CAM_START_CB4_TX_FAIL    = (POCB_FC_CAM_COMM_NG + 10);  //TSTART2
  POCB_FC_CAM_START_CB4_NAK        = (POCB_FC_CAM_COMM_NG + 11);
  POCB_FC_CAM_START_CB4_TIMEOUT    = (POCB_FC_CAM_COMM_NG + 12);
  POCB_FC_CAM_START_EXTRA_TX_FAIL  = (POCB_FC_CAM_COMM_NG + 13);  //RSTDONE
  POCB_FC_CAM_START_EXTRA_NAK      = (POCB_FC_CAM_COMM_NG + 14);
  POCB_FC_CAM_START_EXTRA_TIMEOUT  = (POCB_FC_CAM_COMM_NG + 15);
  POCB_FC_CAM_TEND_NG              = (POCB_FC_CAM_COMM_NG + 16); // TEND
  POCB_FC_CAM_TEND_UNITFORMITY_NG  = (POCB_FC_CAM_COMM_NG + 17);

  POCB_FC_CAM_FAILREASON_BASE = (POCB_FC_CAM_COMM_NG + 20);  //TBD:GAGO:NEWFLOW?


implementation

end.
