program POCB_A2CHv4_Simulator;

uses
  madExcept,
  madLinkDisAsm,
  madListHardware,
  madListProcesses,
  madListModules,
  Vcl.Forms,
  ABout in 'ABout.pas' {frmAbout},
  CommonClass in 'CommonClass.pas',
  DefGmes in 'DefGmes.pas',
  DefModelInfo in 'DefModelInfo.pas',
  DefPG in 'DefPG.pas',
  DefPocb in 'DefPocb.pas',
  GenQueue in 'GenQueue.pas',
  SwitchBtn in 'SwitchBtn.pas',
  LogIn in 'LogIn.pas' {frmLogIn},
  Vcl.Themes,
  Vcl.Styles,
  PwdChange in 'PwdChange.pas' {frmChangePassword},
  SystemSetup in 'SystemSetup.pas' {frmSystemSetup},
  HandBCR in 'HandBCR.pas',
  UdpServerPocb in 'UdpServerPocb.pas',
  DefCam in 'DefCam.pas',
  CamComm in 'CamComm.pas',
  LogicPocb in 'LogicPocb.pas',
  System.SysUtils,
  System.Win.ComObj,
  ExPat in 'ExPat.pas' {frmExPat},
  UserID in 'UserID.pas' {UserIdDlg},
  GMesCom in 'GMesCom.pas',
  DefDio in 'DefDio.pas',
  JigControl in 'JigControl.pas',
  AxtCAMCFS20 in 'EzSoftwareAXT\AxtCAMCFS20.pas',
  AxtDIO in 'EzSoftwareAXT\AxtDIO.pas',
  AxtLIB in 'EzSoftwareAXT\AxtLIB.pas',
  AxtLIBDef in 'EzSoftwareAXT\AxtLIBDef.pas',
  CAMCFSDef in 'EzSoftwareAXT\CAMCFSDef.pas',
  DIODef in 'EzSoftwareAXT\DIODef.pas',
  MotionCtl in 'MotionCtl.pas',
  MotionCtlAxt in 'MotionCtlAxt.pas',
  MotionCtlEzi in 'MotionCtlEzi.pas',
  DefMotion in 'DefMotion.pas',
  DioCtl in 'DioCtl.pas',
  DioCtlAxt in 'DioCtlAxt.pas',
  EziMLDef in 'EziML\EziMLDef.pas',
  EziMLLIB in 'EziML\EziMLLIB.pas',
  DefSerialComm in 'DefSerialComm.pas',
  Alarm in 'Alarm.pas' {frmAlarm},
  EMSAlarmMsg in 'EMSAlarmMsg.pas' {frmEMSAlarmMsg},
  DfsFtpPocb in 'DfsFtpPocb.pas',
  ExLightCtl in 'ExLightCtl.pas',
  SafetyAlarmMsg in 'SafetyAlarmMsg.pas' {frmSafetyAlarmMsg},
  AXA in 'EzSoftwareUC\AXA.pas',
  AXC in 'EzSoftwareUC\AXC.pas',
  AXD in 'EzSoftwareUC\AXD.pas',
  AXDev in 'EzSoftwareUC\AXDev.pas',
  AXHD in 'EzSoftwareUC\AXHD.pas',
  AXHS in 'EzSoftwareUC\AXHS.pas',
  AXL in 'EzSoftwareUC\AXL.pas',
  AXM in 'EzSoftwareUC\AXM.pas',
  MotionCtlAxm in 'MotionCtlAxm.pas',
  DefEfu in 'DefEfu.pas',
  EfuCtl in 'EfuCtl.pas',
  DefIonizer in 'DefIonizer.pas',
  IonizerCtl in 'IonizerCtl.pas',
  UserUtils in 'UserUtils.pas',
  SafetyScreen in 'SafetyScreen.pas' {FrmWorkingMsg},
  POCBClass in 'POCBClass.pas',
  Frame_SystemAlarmAV4 in 'Frame_SystemAlarmAV4.pas' {Frame_SystemArmAV4: TFrame},
  CustomFrame in 'CustomFrame.pas' {CustomFrame: TFrame},
  DiSimul in 'DiSimul.pas' {TDiTestForm},
  MainPocb_A2CH in 'MainPocb_A2CH.pas' {frmMain},
  Mainter_A2CH in 'Mainter_A2CH.pas' {frmMainter},
  ModelInfo_A2CH in 'ModelInfo_A2CH.pas' {frmModelInfo},
  ModelSelect_A2CH in 'ModelSelect_A2CH.pas' {frmSelectModel},
  DefRobot in 'DefRobot.pas',
  RobotCtl in 'RobotCtl.pas',
  DownloadBmpPg in 'DownloadBmpPg.pas' {frmDownloadBmpPg},
  DownloadFwPg in 'DownloadFwPg.pas' {frmDownloadFwPg},
  DownloadFwSpi in 'DownloadFwSpi.pas' {frmDownloadFwSpi},
  Test1Ch_A2CH in 'Test1Ch_A2CH.pas' {frmTest1Ch},
  DefAimf in 'DefAimf.pas',
  UpdateSupport in 'UpdateSupport.pas',
  WarningMsgAutoUpdate in 'WarningMsgAutoUpdate.pas' {frmWarnMsgAim};

{$R *.res}

begin
//  ReportMemoryLeaksOnShutdown := True;
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  TStyleManager.TrySetStyle('Windows10');
  Application.CreateForm(TfrmMain, frmMain);
  Application.CreateForm(TfrmSafetyAlarmMsg, frmSafetyAlarmMsg);
  Application.CreateForm(TfrmWarnMsgAim, frmWarnMsgAim);
  Application.Run;

end.
